### ISSUE TITLE
libcaffe.so: undefined symbol: _ZN2

### ISSUE THREAD

**Issue by gopi77** [torrvision/crfasrnn#124]
Pasted the error below.
gopi@gp:~/crfasrnn/python-scripts$ python crfasrnn_demo.py
Traceback (most recent call last):
  File "crfasrnn_demo.py", line 31, in <module>
    import caffe
  File "../caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "../caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: /home/gopi/crfasrnn/python-scripts/../caffe/python/caffe/../../build/lib/libcaffe.so: undefined symbol: _ZN2cv8imencodeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_11_InputArrayERSt6vectorIhSaIhEERKSB_IiSaIiEE

My system details:
Ubuntu 16.04 with nvidia gtx 1070 GPU.

FYI, also tried Uncommenting the line:
WITH_PYTHON_LAYER := 1 as per https://github.com/BVLC/caffe/issues/3834 & did make again, but no improvement

**Comment by gopi77** [comment]
I solved it using default python instead of anaconda.
gopi@gp:~/crfasrnn/python-scripts$ /usr/bin/python crfasrnn_demo.py

Ref: https://github.com/BVLC/caffe/issues/5090
http://stackoverflow.com/questions/24664435/use-default-python-rather-than-anaconda-installation-when-called-from-the-termin
