### ISSUE TITLE
Training with my own data : Multiple problems arising

### ISSUE THREAD

**Issue by matthiasmace** [torrvision/crfasrnn#152]
Hello
I am trying to train cfrasrnn with my own data using https://github.com/martinkersner/train-CRF-RNN/
I had to slightly modify some pieces of the code to make it run on my Mac (OSX.12) but it now runs the training.
I have one first problem when trying to parse the log file in order to vizualise loss (using loss_from_log.py https://github.com/martinkersner/train-CRF-RNN/blob/master/loss_from_log.py) : 
_Traceback (most recent call last):
  File "loss_from_log.py", line 123, in <module>
    main()
  File "loss_from_log.py", line 43, in main
    train_loss.append(float(matched.group(1)))
AttributeError: 'NoneType' object has no attribute 'group'_

Strange behavior since the log file DOES contain the parsed objects.

The second is that when I try to use the caffemodel output (e.g. iteration 5000 or 7000) to test if it recognizes object, it now fails to do so (I tried with various objects).
What am I doing wrong please ?
Many thanks if any one can help !

**Comment by Sam813** [comment]
@matthiasmace I have the same problem with loss_from_log. 
Have you solved it?
