### ISSUE TITLE
Error while running crfasrnn_demo.py - No module named loggingnet

### ISSUE THREAD

**Issue by limorbagizada** [torrvision/crfasrnn#24]
Hii, when I run the crfasrnn_demo.py, I tackle the following error:

File "crfasrnn-master/python-scripts/crfasrnn_demo.py", line 22, in <module>
    import loggingnet
ImportError: No module named loggingnet

I am new with caffe but I tried the default caffe demo (come with the caffe environment) and it worked correctly, and all the requirements have been installed (I use Anaconda 2 for Python).

Maybe this error occur due to wrong environment settings?
My Environment Variables are:
1. PYTHONPATH=/home/limor/anaconda2/lib/python2.7:/home/limor/caffe-master/python:
2. LD_LIBRARY_PATH=/usr/local/cuda-7.5/lib64:
3. PATH=/usr/local/cuda-7.5/bin:/home/limor/anaconda2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
4. CAFFE_ROOT=/home/limor/caffe-master

**Comment by bittnt** [comment]
Hi, 

First, make sure you have all the caffe dependencies installed and caffe and pycaffe are being properly compiled. Then, you should check if there is any spelling mistakes in your python script, e.g. we do not have loggingnet, we have logging. so you should only have "import logging". This is one dependencies that is required by caffe.

**Comment by limorbagizada** [comment]
Thanks!
It was a spelling mistake in my script, I change it to "logging" and it is ok. but the I tackle different error: 
  File "crfasrnn-master/python-scripts/crfasrnn_demo.py", line 40, in <module>
    net = caffe.Segmenter(MODEL_FILE, PRETRAINED)
AttributeError: 'module' object has no attribute 'Segmenter'

I see that the Segmenter is located in : "/home/limor/crfasrnn-master/caffe-crfrnn/python/caffe".

Note that:  all the caffe dependencies have been installed and caffe and pycaffe are build successfully. I can run other caffe-demoes.

**Comment by bittnt** [comment]
You should run the demo from this repository and use the caffe code from this repository.

**Comment by limorbagizada** [comment]
I'm not sure that I understand what do you mean - 
Do you mean to change the CAFFE_ROOT environment variable to the location of the segmenter or to accese to the location of the segmenter and run the crfasrnn_demo.py as follow: 
limor@Dp25439-linux:~/crfasrnn-master/caffe-crfrnn/python/caffe$ python ~/crfasrnn-master/python-scripts/crfasrnn_demo.py
or maybe something else?

(I tried the suggestion I mention above but it doesnt work)
Thanks a lot for your assistance!

**Comment by qizhuli** [comment]
1. `cd ~/crfasrnn-master/python-scripts/`
2. run `python ~/crfasrnn-master/python-scripts/crfasrnn_demo.py`
Hope it helps!

**Comment by limorbagizada** [comment]
Thanks!!
When I run the demo from this repository, I have this error:
Traceback (most recent call last):
  File "crfasrnn_demo.py", line 24, in <module>
    import numpy as np
  File "/home/limor/anaconda2/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/home/limor/anaconda2/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/limor/anaconda2/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/limor/anaconda2/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/limor/anaconda2/lib/python2.7/site-packages/numpy/core/__init__.py", line 57, in <module>
    from numpy.testing import Tester
  File "/home/limor/anaconda2/lib/python2.7/site-packages/numpy/testing/__init__.py", line 14, in <module>
    from .utils import *
  File "/home/limor/anaconda2/lib/python2.7/site-packages/numpy/testing/utils.py", line 15, in <module>
    from tempfile import mkdtemp
  File "/home/limor/anaconda2/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/home/limor/caffe-master/distribute/python/caffe/io.py", line 2, in <module>
    import skimage.io
  File "/home/limor/anaconda2/lib/python2.7/site-packages/skimage/__init__.py", line 111, in <module>
    from .util.dtype import *
  File "/home/limor/anaconda2/lib/python2.7/site-packages/skimage/util/__init__.py", line 1, in <module>
    from .dtype import (img_as_float, img_as_int, img_as_uint, img_as_ubyte,
  File "/home/limor/anaconda2/lib/python2.7/site-packages/skimage/util/dtype.py", line 8, in <module>
    dtype_range = {np.bool_: (False, True),
AttributeError: 'module' object has no attribute 'bool_'


I think that the error comes from loading "io.py" from wrong folder. This means that the numpy load other "io.py" instead of its own.

When I load the demo from different folder I didnt tackle this error, but then the Segmenter doesn't load (the [previous error)

my PYTHONPATH is as follow:
export PYTHONPATH="/home/limor/anaconda2/lib/python2.7:$PYTHONPATH"
export PYTHONPATH="/home/limor/caffe-master/python:$PYTHONPATH"
export PYTHONPATH="/home/limor/caffe-master/distribute/python/caffe:$PYTHONPATH"

How can I fix this problem?
Thank you!

**Comment by qizhuli** [comment]
Okay, `PYTHONPATH` should be `~/caffe-master/distribute/python` instead of `~/caffe-master/distribute/python/caffe`.
Also, do not run python code from the `caffe/python` dir.

**Comment by limorbagizada** [comment]
Thanks it help!
but now it cant find caffe module

Traceback (most recent call last):
  File "crfasrnn_demo.py", line 29, in <module>
    import caffe
  File "../caffe-crfrnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "../caffe-crfrnn/python/caffe/pycaffe.py", line 10, in <module>
    from ._caffe import Net, SGDSolver
ImportError: No module named _caffe

Should I add also "/home/limor/crfasrnn-master/caffe-crfrnn/python" to thePYTHONPATH?

thanks!

**Comment by limorbagizada** [comment]
I add "/home/limor/caffe-master/distribute/lib" to the LD_LIBRARY_PATH but it still doesn't work :(

**Comment by qizhuli** [comment]
Do you have `_caffe.so` in `/home/limor/caffe-master/python/caffe/`?

**Comment by limorbagizada** [comment]
Yes, I have

**Comment by limorbagizada** [comment]
Do you know how to fix this error?
Thanks.

**Comment by limorbagizada** [comment]
It work!!
I need to do make pycaffe from crfasrnn-master/python-scripts
in addition to the mske pycaffe from thr master-caffe directory. 
Thanks alot!
Now it work and produce an output

**Comment by tsandesh1** [comment]
How did you solve this? I got " 'module' object has no attribute 'Segmenter' " error while using net = caffe.Segmenter(MODEL_FILE, PRETRAINED). I have successfully installed pycaffe and tested as well. For eg: If I use net = caffe.Net('conv.prototxt', caffe.TEST), it works properly. Do you know the reason? And can you please write step by step that how did you solve this issue?

**Comment by kunsa** [comment]
@limorbagizada could u describe it in detail？
